name: notification-consumer CI

on:
  push:
    paths:
      - 'notification-consumer/**'
    branches:
      - main
  workflow_dispatch:

env:
  RELEASE_LABEL: ${{ github.sha }}
  APP_NAME: notification-consumer

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests
        working-directory: ${{ env.APP_NAME }}
        run: mvn clean verify

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        working-directory: ${{ env.APP_NAME }}
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_NAME }}
          push: true
          tags: ${{ env.APP_NAME }}:${{ env.RELEASE_LABEL }}